"""논문 Word 파일 생성 스크립트"""
from docx import Document
from docx.shared import Pt, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn

doc = Document()

# ── 기본 스타일 설정 ──
style = doc.styles['Normal']
font = style.font
font.name = '맑은 고딕'
font.size = Pt(10)

# ============================================================
# 제목
# ============================================================
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = p.add_run('RAPTOR 기반 선택지 집합 생성과 스마트카드 매칭을 활용한\n대중교통 경로선택 모델')
run.bold = True
run.font.size = Pt(16)

p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = p.add_run('Transit Route Choice Model Using RAPTOR-Based Choice Set Generation\nand Smart Card Data Matching')
run.font.size = Pt(12)
run.italic = True

# 저자
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = p.add_run('김민수')
run.font.size = Pt(11)

doc.add_paragraph()  # 빈 줄

# ============================================================
# 초록
# ============================================================
doc.add_heading('초록', level=1)

doc.add_paragraph(
    '대중교통 수요 시뮬레이션의 핵심은 이용자의 경로선택 행태를 정확히 재현하는 것이다. '
    '그러나 대중교통 경로선택은 수단 환승, 노선 조합, 배차간격 등 복합적 요인이 작용하여 모형화가 어렵다. '
    '특히 수도권과 같이 버스·도시철도·광역급행철도(GTX)가 혼재된 대규모 네트워크에서는 '
    '설문 기반 선호의향(SP) 조사의 비용과 표본 한계가 실용적 장벽이 된다.'
)
doc.add_paragraph(
    '본 연구는 수도권 스마트카드 약 3,700만 통행 기록과 오픈소스 경로탐색엔진 OpenTripPlanner(OTP)의 '
    '대안경로를 유사도 매칭(similarity matching)하여 경로선택 관측치를 구축하고, '
    '다항로짓(Multinomial Logit, MNL) 모형의 파라미터를 추정하였다. '
    '유사도 지표는 노선 Jaccard, 정류장 순서 LCS, 수단구성의 3단계 복합지표로 구성하며, '
    '2단계 격자탐색(grid search)을 통해 최적 가중치(mode 0.83, sequence 0.14, route 0.03)와 '
    '임계값(composite ≥ 0.5, sequence gate ≥ 0.3)을 결정하였다.'
)
doc.add_paragraph(
    '추정 결과 MNL 모형은 McFadden ρ² = 0.530, 제1순위 예측정확도(FPR) 72.5%를 달성하였으며, '
    '수단분담률 재현에서도 철도전용·버스전용·환승 카테고리 모두 실측 대비 1%p 이내의 정밀도를 보였다. '
    '환승횟수(β = −3.40)가 가장 큰 억제 요인이었으며, 철도 이용(β = +2.58)은 양의 효용을 보여 '
    '도시철도 선호 경향을 확인하였다. 접근·이탈 도보시간은 로그 변환(log(1+x))이 적합하였고, '
    '버스유형별 차등요금 반영으로 요금 파라미터(β = −0.41)를 성공적으로 식별하였다. '
    '나아가 MNL을 기반으로 5종의 딥러닝 모형(DNN, TasteNet, ResLogit, ASU-DNN, L-MNL)을 '
    '추정한 결과, ASU-DNN이 ρ² = 0.686, FPR 76.0%로 최고 성능을 달성하였다. '
    'SHAP 분석을 통해 딥러닝 모형의 변수 중요도가 MNL 해석과 일관됨을 확인하였다. '
    '본 연구는 별도의 설문조사 없이 교통카드 빅데이터만으로 경로선택 모형을 추정할 수 있는 '
    '파이프라인을 제시하였으며, GTX-B·C 등 신규 노선 개통 시 수요 전환 시뮬레이션에 활용 가능하다.'
)

p = doc.add_paragraph()
run = p.add_run('핵심어: ')
run.bold = True
p.add_run('경로선택모형, 스마트카드, 유사도 매칭, 다항로짓, 대중교통 수요 시뮬레이션, OpenTripPlanner')

# ============================================================
# Abstract (영문)
# ============================================================
doc.add_heading('Abstract', level=1)

doc.add_paragraph(
    'This study proposes a pipeline for estimating public transit route choice models '
    'using smart card big data without requiring stated-preference surveys. '
    'Approximately 37 million smart card trip records in the Seoul metropolitan area '
    'are matched with alternative routes generated by OpenTripPlanner (OTP) through '
    'a three-level composite similarity metric comprising route Jaccard similarity, '
    'stop-sequence LCS ratio, and mode composition matching. '
    'Optimal similarity weights and thresholds are determined via a two-stage grid search. '
    'A multinomial logit (MNL) model is estimated with nine variables including total in-vehicle time, '
    'log-transformed access/egress walk time, number of transfers, fare, and mode-specific constants. '
    'The MNL model achieves McFadden ρ² = 0.530 and first-place recovery rate of 72.5%, '
    'with mode share replication within 1 percentage point across all major categories. '
    'Five deep learning models (DNN, TasteNet, ResLogit, ASU-DNN, L-MNL) are further estimated '
    'on the MNL-based training data, with ASU-DNN achieving the best performance '
    '(ρ² = 0.686, FPR = 76.0%). '
    'SHAP analysis confirms that variable importance rankings are consistent across '
    'MNL and deep learning models. '
    'The framework enables demand simulation for new transit services such as GTX-B and GTX-C lines.'
)

p = doc.add_paragraph()
run = p.add_run('Keywords: ')
run.bold = True
p.add_run('route choice model, smart card, similarity matching, multinomial logit, '
          'public transit simulation, OpenTripPlanner')

# ============================================================
# 1. 서론
# ============================================================
doc.add_heading('1. 서론', level=1)

doc.add_heading('1.1 연구 배경', level=2)
doc.add_paragraph(
    '대중교통 수요예측은 신규 노선 건설, 요금 정책 수립, 배차 계획 등 교통정책의 핵심 근거를 제공한다. '
    '수요예측의 정확도는 이용자의 경로선택 행태를 얼마나 충실히 재현하느냐에 달려 있으며, '
    '이를 위해 다항로짓(MNL), 혼합로짓(Mixed Logit) 등 이산선택모형이 널리 사용된다. '
    '그러나 대중교통 경로선택은 승용차 경로선택과 달리 수단 환승, 노선 조합, 배차간격, '
    '도보접근 등 복합적 요인이 작용하여 모형화의 난이도가 높다.'
)
doc.add_paragraph(
    '전통적으로 경로선택 모형의 파라미터 추정에는 설문 기반 선호의향(SP) 조사 데이터가 사용되어 왔다. '
    '그러나 SP 조사는 비용이 크고, 응답자의 가상 선택이 실제 행태와 괴리될 수 있으며, '
    '표본 규모의 한계로 대규모 네트워크의 다양한 OD(기종점) 패턴을 포괄하기 어렵다. '
    '반면 스마트카드(교통카드) 데이터는 수천만 건의 실제 통행 기록을 제공하지만, '
    '이용자가 어떤 대안경로 집합에서 선택했는지를 직접 관측할 수 없다는 근본적 한계가 있다.'
)

doc.add_heading('1.2 연구 목적', level=2)
doc.add_paragraph(
    '본 연구는 이러한 한계를 극복하기 위해, 스마트카드 실측 통행과 경로탐색엔진(OTP) 대안경로를 '
    '유사도 매칭함으로써 경로선택 관측치를 자동 구축하는 파이프라인을 제안한다. '
    '구체적인 연구 목적은 다음과 같다:'
)
doc.add_paragraph('(1) 스마트카드 통행 기록으로부터 OD쌍을 추출하고, OTP 대안경로와 매칭하여 경로선택 훈련 데이터를 구축한다.', style='List Number')
doc.add_paragraph('(2) 유사도 지표의 가중치와 임계값을 체계적 탐색(grid search)으로 최적화한다.', style='List Number')
doc.add_paragraph('(3) MNL 모형을 추정하여 경로선택 행태의 주요 영향요인을 분석한다.', style='List Number')
doc.add_paragraph('(4) GTX 등 신규 교통수단 도입 시 수요 전환 시뮬레이션의 기반을 마련한다.', style='List Number')

doc.add_heading('1.3 연구 범위', level=2)
doc.add_paragraph(
    '본 연구의 공간적 범위는 수도권(서울·경기·인천)이며, 분석 대상은 2022년 스마트카드 통행 기록 '
    '약 3,700만 건이다. 교통수단은 시내버스, 도시철도(지하철), 광역급행철도(GTX-A)를 포함하며, '
    'OTP에 의한 대안경로 생성 시 최대 10개 경로를 탐색하였다.'
)

# ============================================================
# 2. 선행연구 검토
# ============================================================
doc.add_heading('2. 선행연구 검토', level=1)

doc.add_heading('2.1 대중교통 경로선택 모형', level=2)
doc.add_paragraph(
    '대중교통 경로선택 모형은 Dial(1971)의 STOCH 모형 이후 꾸준히 발전해 왔다. '
    'Ben-Akiva and Lerman(1985)은 이산선택이론에 기반한 MNL 모형을 대중교통에 적용하였으며, '
    '이후 경로 간 상관을 반영하는 C-Logit(Cascetta et al., 1996), '
    'Path Size Logit(Ben-Akiva and Bierlaire, 1999; Tan et al., 2015), '
    'Mixed Logit(McFadden and Train, 2000) 등이 제안되었다. '
    'Nassir et al.(2019)은 스마트카드 데이터를 활용한 전략 기반 재귀 경로선택 모형을 제안하여 '
    '고빈도 대중교통 서비스에서의 경로선택 행태를 분석하였다.'
)
doc.add_paragraph(
    '최근에는 딥러닝 기반 모형이 활발히 연구되고 있다. '
    'Sifringer et al.(2020)은 TasteNet을 통해 컨텍스트 의존적 파라미터를 학습하였고, '
    'Wong and Farooq(2021)은 ResLogit으로 MNL 위에 비선형 잔차를 학습하는 구조를 제안하였다. '
    'Han et al.(2022)은 DNN 표현학습과 MNL을 결합한 L-MNL을 제시하였다. '
    'Marra and Corman(2025)은 대중교통 경로선택에 딥러닝을 적용하여 PSL을 상회하는 성능을 보고하였으나, '
    '단일 DL 모형과의 비교에 그쳐 다양한 DL 구조 간 체계적 비교는 부족하였다. '
    'Hillel et al.(2021)은 ML 기반 수단선택 모형에 대한 체계적 리뷰에서 '
    '해석력 부족이 실무 적용의 주요 장벽임을 지적하였다.'
)

doc.add_heading('2.2 스마트카드 데이터 활용 연구', level=2)
doc.add_paragraph(
    '스마트카드 데이터를 활용한 대중교통 분석은 주로 통행패턴 분석, OD 추정, '
    '환승행태 분석 등에 집중되어 왔다. '
    'Pelletier et al.(2011)은 스마트카드 데이터의 교통계획 활용을 체계적으로 정리하였다. '
    'Zhao et al.(2017)은 심천 지하철에서 AFC 데이터 기반 확률적 경로배정 모형을 제안하였으나, '
    '도시철도 단독 네트워크에 한정되었다. '
    'Arriagada et al.(2025)은 산티아고에서 신규 지하철 개통 전후 스마트카드 데이터를 활용하여 '
    '경험학습(experiential learning) 기반 경로선택 모형을 추정하였다.'
)
doc.add_paragraph(
    '그러나 스마트카드 데이터를 버스·도시철도·GTX 등 다수단 네트워크의 경로선택 모형 '
    '훈련 데이터로 직접 활용한 연구는 제한적이다. '
    '스마트카드는 승·하차 정류장과 시각만 기록하므로, 이용자가 실제로 거부한 대안경로를 '
    '관측할 수 없기 때문이다. 본 연구는 이 간극을 경로탐색엔진의 대안경로 생성과 '
    '유사도 매칭으로 메우고자 한다.'
)

doc.add_heading('2.3 대안경로 집합 생성', level=2)
doc.add_paragraph(
    '경로선택 모형의 품질은 대안경로 집합(choice set)의 구성에 크게 의존한다. '
    'Marra and Corman(2020)은 취리히에서 GPS 추적 데이터 기반으로 '
    '효율적이고 정밀한 대안경로 집합 구성 기준을 제안하였으나, '
    'GPS 추적의 소규모 표본이라는 한계가 있었다. '
    'Tomhave and Khani(2022)는 미니애폴리스에서 다기준 대안경로 생성 알고리즘을 개발하고 '
    '집합 품질이 모형 추정에 미치는 영향을 분석하였으나, 설문 기반 RP 데이터에 의존하였다.'
)
doc.add_paragraph(
    'OpenTripPlanner(OTP)는 GTFS 기반 오픈소스 멀티모달 경로탐색엔진으로, '
    'RAPTOR 알고리즘(Delling et al., 2015)에 기반하여 K-best 대안경로를 효율적으로 생성한다. '
    'Bast et al.(2016)은 대중교통 경로탐색 알고리즘을 종합적으로 비교하여 '
    'RAPTOR의 대규모 네트워크 적용 가능성을 확인하였다. '
    '본 연구는 OTP의 K-best 경로를 대안경로 집합으로 활용하되, '
    '스마트카드 실측 통행과의 유사도 매칭을 통해 선택확률을 부여하는 방식을 채택하였다.'
)

doc.add_heading('2.4 딥러닝 해석력과 SHAP 분석', level=2)
doc.add_paragraph(
    '딥러닝 모형의 해석력 부족은 교통 분야 실무 적용의 주요 장벽으로 지적되어 왔다. '
    'Lundberg and Lee(2017)가 제안한 SHAP(SHapley Additive exPlanations)은 '
    '게임이론 기반으로 각 변수의 한계기여를 공정하게 배분하는 방법론이다. '
    'Koushik et al.(2024)은 ANN 기반 수단선택 모형에 SHAP을 적용하여 '
    '변수 중요도와 오분류 패턴을 분석하였으며, '
    'Tang et al.(2024)은 청두에서 신경망+SHAP 기반 수단선택 예측을 수행하였다. '
    '그러나 이들 연구는 모두 수단선택(mode choice)에 한정되어 있으며, '
    '경로선택(route choice) 영역에서 다수의 DL 모형에 SHAP을 적용한 연구는 '
    '본 연구가 최초의 시도이다.'
)

# ============================================================
# 3. 방법론
# ============================================================
doc.add_heading('3. 방법론', level=1)

doc.add_heading('3.1 전체 파이프라인', level=2)
doc.add_paragraph(
    '본 연구의 방법론은 크게 4단계로 구성된다: '
    '(1) 스마트카드 데이터 전처리 및 통행사슬(Trip Chain Network, TCN) 구축, '
    '(2) OTP 대안경로 생성, '
    '(3) 유사도 매칭 및 훈련 데이터 구축, '
    '(4) MNL 모형 추정. '
    '각 단계의 상세 내용은 아래와 같다.'
)

doc.add_heading('3.2 스마트카드 데이터 전처리', level=2)
doc.add_paragraph(
    '수도권 스마트카드 약 3,700만 통행 기록(2022년)을 대상으로 승·하차 정류장 및 시각 정보를 추출하였다. '
    '개별 환승 레코드(TCD)를 통행사슬 네트워크(TCN) 형태로 변환하여, '
    '한 통행(trip)이 한 행(row)으로 표현되도록 구조화하였다. '
    '이 과정에서 다음의 핵심 처리를 수행하였다.'
)
doc.add_paragraph(
    '첫째, 노선-정류장 매핑(ROUTESTTN) 기반으로 정류장 좌표·명칭·순서를 부여하였다. '
    '둘째, 도시철도 환승의 경우 스마트카드에 단일 레코드로 기록되나 실제로는 다른 노선으로 '
    '환승하는 "숨겨진 환승"이 존재한다. 이를 BFS(너비우선탐색) 기반 그래프 탐색으로 탐지하여 '
    '환승역과 환승횟수를 복원하였다. 예를 들어, 수인분당선에서 2호선으로의 환승 시 '
    '선릉역이 숨겨진 환승역으로 탐지된다. '
    '셋째, 각 통행의 교통수단 조합을 7개 카테고리(버스전용, 철도전용, GTX전용, '
    '버스+철도, 버스+GTX, 철도+GTX, 버스+철도+GTX)로 분류하였다.'
)
doc.add_paragraph(
    '전처리된 TCN 데이터에서 OD쌍을 추출하고, 통행 건수를 집계하여 '
    '총 336,498개의 고유 OD쌍에 대한 OTP 경로탐색 입력 데이터를 생성하였다.'
)

doc.add_heading('3.3 OTP 대안경로 생성', level=2)
doc.add_paragraph(
    'OpenTripPlanner(OTP)에 수도권 GTFS 데이터(6,134개 노선)를 적재하고, '
    '각 OD쌍에 대해 최대 10개의 대안경로를 탐색하였다. 탐색 시간창(search window)은 '
    '7,200초(2시간)로 설정하여 충분한 대안 다양성을 확보하였다. '
    'OTP 응답으로부터 각 대안경로의 구간(leg)별 교통수단, 노선명, 정류장 시퀀스, '
    '소요시간, 거리, 요금 등 속성을 추출하였다.'
)
doc.add_paragraph(
    '동일 구조(수단+노선+정류장)에 출발시간만 다른 중복 경로는 합산하고 소요시간은 평균하여 '
    '중복을 제거하였다. 또한 transit leg의 거리가 0으로 기록되는 경우, '
    'legGeometry polyline에서 좌표를 복원하여 haversine 거리를 재계산하였다.'
)

doc.add_heading('3.4 유사도 매칭', level=2)

doc.add_heading('3.4.1 3단계 복합유사도 지표', level=3)
doc.add_paragraph(
    '스마트카드 실측 통행과 OTP 대안경로를 매칭하기 위해 3단계 복합유사도 지표를 설계하였다. '
    'OTP와 스마트카드는 서로 다른 ID 체계를 사용하므로, 노선명·정류장명 등 명칭(name) 기반으로 비교하며, '
    '정규화 규칙(서울 접두사 제거, 번호 접미사 제거, fuzzy 매칭 등)을 적용하였다.'
)

# 유사도 지표 표
table = doc.add_table(rows=4, cols=4, style='Table Grid')
headers = ['레벨', '지표', '가중치', '설명']
for i, h in enumerate(headers):
    table.rows[0].cells[i].text = h
    for paragraph in table.rows[0].cells[i].paragraphs:
        for run in paragraph.runs:
            run.bold = True

data = [
    ['수단구성(Mode)', 'Mode matching', '0.83', '교통수단 조합 일치도 (지배적 변별 요소)'],
    ['정류장 순서(Sequence)', 'LCS ratio', '0.14', '정류장 시퀀스의 최장공통부분수열 비율'],
    ['노선(Route)', 'Jaccard similarity', '0.03', '이용 노선 집합의 Jaccard 유사도'],
]
for r, row_data in enumerate(data, 1):
    for c, val in enumerate(row_data):
        table.rows[r].cells[c].text = val

doc.add_paragraph()

doc.add_paragraph(
    '복합유사도 점수는 다음과 같이 산출된다:'
)
doc.add_paragraph(
    '    composite = 0.83 × mode_match + 0.14 × seq_lcs + 0.03 × route_jaccard'
)

doc.add_paragraph()
p = doc.add_paragraph()
run = p.add_run('각 지표의 상세 정의와 계산 방법은 다음과 같다.')
run.bold = True

# ── (1) 노선 유사도 ──
doc.add_paragraph()
p = doc.add_paragraph()
run = p.add_run('(1) 노선 유사도 (Route Jaccard Similarity)')
run.bold = True

doc.add_paragraph(
    '스마트카드 통행에서 이용한 노선 집합과 OTP 대안경로의 노선 집합을 비교한다. '
    'Jaccard 유사도는 두 집합의 교집합 크기를 합집합 크기로 나눈 값이다.'
)
doc.add_paragraph(
    '    J(A, B) = |A ∩ B| / |A ∪ B|'
)
doc.add_paragraph(
    '여기서 A는 스마트카드 통행의 노선 집합, B는 OTP 대안경로의 노선 집합이다. '
    '노선명은 정규화 규칙을 적용하여 비교한다(예: OTP "서울2호선" → "2호선", '
    'SC "5531번(군포동행정복지센터방면)" → "5531").'
)

# 예시 표
doc.add_paragraph()
p = doc.add_paragraph()
run = p.add_run('예시:')
run.italic = True

table = doc.add_table(rows=4, cols=3, style='Table Grid')
headers = ['', 'SC 통행', 'OTP 대안경로']
for i, h in enumerate(headers):
    table.rows[0].cells[i].text = h
    for paragraph in table.rows[0].cells[i].paragraphs:
        for run in paragraph.runs:
            run.bold = True
ex1 = [
    ['노선 집합', '{2호선, 신분당선}', '{2호선, 신분당선}'],
    ['교집합 / 합집합', '', '{2호선, 신분당선} / {2호선, 신분당선}'],
    ['route_jaccard', '', '2/2 = 1.00 (완전 일치)'],
]
for r, row_data in enumerate(ex1, 1):
    for c, val in enumerate(row_data):
        table.rows[r].cells[c].text = val

doc.add_paragraph()
table = doc.add_table(rows=4, cols=3, style='Table Grid')
for i, h in enumerate(['', 'SC 통행', 'OTP 대안경로']):
    table.rows[0].cells[i].text = h
    for paragraph in table.rows[0].cells[i].paragraphs:
        for run in paragraph.runs:
            run.bold = True
ex2 = [
    ['노선 집합', '{7호선, 2호선}', '{7호선, 9호선}'],
    ['교집합 / 합집합', '', '{7호선} / {7호선, 2호선, 9호선}'],
    ['route_jaccard', '', '1/3 = 0.33 (부분 일치)'],
]
for r, row_data in enumerate(ex2, 1):
    for c, val in enumerate(row_data):
        table.rows[r].cells[c].text = val

# ── (2) 정류장 순서 유사도 ──
doc.add_paragraph()
p = doc.add_paragraph()
run = p.add_run('(2) 정류장 순서 유사도 (Sequence LCS Ratio)')
run.bold = True

doc.add_paragraph(
    '스마트카드 통행의 경유 정류장 시퀀스와 OTP 대안경로의 정류장 시퀀스에 대해 '
    '최장공통부분수열(Longest Common Subsequence, LCS)의 길이를 산출하고, '
    '양쪽 시퀀스 길이의 최댓값으로 정규화한다.'
)
doc.add_paragraph(
    '    seq_lcs = LCS(S_sc, S_otp) / max(|S_sc|, |S_otp|)'
)
doc.add_paragraph(
    'LCS는 순서를 보존하면서 공통으로 나타나는 가장 긴 부분수열로, '
    '단순 집합 비교(Jaccard)와 달리 정류장의 방문 순서까지 반영한다. '
    '이를 통해 같은 노선을 이용하되 역방향이거나 경유지를 거치는 우회 통행을 감별할 수 있다. '
    '정류장명은 OTP의 복합명(예: "군포1동행정복지센터.군포역")을 "." 기준으로 분리하여 '
    'SC 명칭(예: "군포역")과 fuzzy 매칭한다.'
)

doc.add_paragraph()
p = doc.add_paragraph()
run = p.add_run('예시: 정상 통행 vs 경유지 통행')
run.italic = True

table = doc.add_table(rows=5, cols=3, style='Table Grid')
for i, h in enumerate(['', '정상 통행', '경유지 통행']):
    table.rows[0].cells[i].text = h
    for paragraph in table.rows[0].cells[i].paragraphs:
        for run in paragraph.runs:
            run.bold = True
ex3 = [
    ['SC 시퀀스', 'A → B → C → D', 'A → X → Y → B → C → D'],
    ['OTP 시퀀스', 'A → B → C → D', 'A → B → C → D'],
    ['LCS', 'ABCD (길이 4)', 'ABCD (길이 4)'],
    ['seq_lcs', '4/4 = 1.00', '4/6 = 0.67'],
]
for r, row_data in enumerate(ex3, 1):
    for c, val in enumerate(row_data):
        table.rows[r].cells[c].text = val

doc.add_paragraph()
doc.add_paragraph(
    '위 예시에서 경유지 통행은 route_jaccard가 높을 수 있으나(같은 노선 이용), '
    'seq_lcs가 낮아져 시퀀스 게이트(≥ 0.3)에 의해 필터링된다.'
)

# ── (3) 수단구성 유사도 ──
doc.add_paragraph()
p = doc.add_paragraph()
run = p.add_run('(3) 수단구성 유사도 (Mode Matching)')
run.bold = True

doc.add_paragraph(
    '스마트카드 통행의 교통수단 집합과 OTP 대안경로의 수단 집합을 비교한다. '
    '수단 유형은 버스(BUS), 도시철도(SUBWAY), 광역급행철도(GTX)로 분류하며, '
    '다음 세 지표의 가중합으로 산출된다.'
)

table = doc.add_table(rows=4, cols=3, style='Table Grid')
for i, h in enumerate(['서브 지표', '가중치', '설명']):
    table.rows[0].cells[i].text = h
    for paragraph in table.rows[0].cells[i].paragraphs:
        for run in paragraph.runs:
            run.bold = True
mode_sub = [
    ['mode_exact', '0.3', '수단 집합 완전 일치 여부 (0 또는 1)'],
    ['mode_jaccard', '0.5', '수단 집합의 Jaccard 유사도'],
    ['mode_contains', '0.2', 'SC 수단이 OTP 수단에 포함되는지 여부'],
]
for r, row_data in enumerate(mode_sub, 1):
    for c, val in enumerate(row_data):
        table.rows[r].cells[c].text = val

doc.add_paragraph()
p = doc.add_paragraph()
run = p.add_run('예시:')
run.italic = True

table = doc.add_table(rows=5, cols=3, style='Table Grid')
for i, h in enumerate(['', '완전 일치', '부분 일치']):
    table.rows[0].cells[i].text = h
    for paragraph in table.rows[0].cells[i].paragraphs:
        for run in paragraph.runs:
            run.bold = True
ex4 = [
    ['SC 수단', '{BUS, SUBWAY}', '{BUS, SUBWAY}'],
    ['OTP 수단', '{BUS, SUBWAY}', '{SUBWAY, GTX}'],
    ['mode_exact / jaccard / contains', '1.0 / 1.0 / 1.0', '0.0 / 0.33 / 0.0'],
    ['mode_match', '0.3×1 + 0.5×1 + 0.2×1 = 1.00', '0.3×0 + 0.5×0.33 + 0.2×0 = 0.17'],
]
for r, row_data in enumerate(ex4, 1):
    for c, val in enumerate(row_data):
        table.rows[r].cells[c].text = val

doc.add_paragraph()

# ── 종합 매칭 예시 ──
p = doc.add_paragraph()
run = p.add_run('(4) 종합 매칭 예시')
run.bold = True

doc.add_paragraph(
    '아래는 하나의 SC 통행(고색→역삼, 수인분당선→2호선)에 대해 '
    'OTP 대안경로 3개와 매칭하는 과정을 예시로 보여준다.'
)

table = doc.add_table(rows=5, cols=6, style='Table Grid')
for i, h in enumerate(['', 'route_jaccard', 'seq_lcs', 'mode_match', 'composite', '판정']):
    table.rows[0].cells[i].text = h
    for paragraph in table.rows[0].cells[i].paragraphs:
        for run in paragraph.runs:
            run.bold = True
ex5 = [
    ['대안1: 수인분당→2호선', '1.00', '0.95', '1.00', '0.83×1.00 + 0.14×0.95 + 0.03×1.00 = 0.99', '매칭 ✓'],
    ['대안2: 1호선→2호선', '0.50', '0.60', '0.50', '0.83×0.50 + 0.14×0.60 + 0.03×0.50 = 0.51', '매칭 ✓'],
    ['대안3: 버스 직행', '0.00', '0.20', '0.00', '0.83×0.00 + 0.14×0.20 + 0.03×0.00 = 0.03', '탈락 ✗'],
    ['대안2 (경유지)', '0.50', '0.25', '0.50', 'seq_lcs < 0.3 → 시퀀스 게이트 탈락', '탈락 ✗'],
]
for r, row_data in enumerate(ex5, 1):
    for c, val in enumerate(row_data):
        table.rows[r].cells[c].text = val

doc.add_paragraph()
doc.add_paragraph(
    '대안1은 노선·정류장·수단 모두 높은 유사도를 보여 composite = 0.99로 매칭된다. '
    '대안2는 노선이 부분적으로 다르지만 composite ≥ 0.5를 충족하여 매칭된다. '
    '대안3은 수단 자체가 다르므로 composite = 0.04로 탈락한다. '
    '마지막 행은 composite는 0.5 이상이더라도 seq_lcs < 0.3이면 '
    '시퀀스 게이트에 의해 경유지 통행으로 판정되어 탈락하는 예시이다.'
)

doc.add_heading('3.4.2 매칭 임계값 및 시퀀스 게이트', level=3)
doc.add_paragraph(
    '매칭 임계값은 composite ≥ 0.5로 설정하였다. 임계값 0.6에서는 OD 수가 급감하고, '
    '0.5에서 성능과 데이터 규모의 균형점이 형성되었다. '
    '추가로 sim_sequence ≥ 0.3의 시퀀스 게이트를 적용하여, '
    '같은 노선을 이용하되 경유지를 거치는 우회 통행을 필터링하였다. '
    '이 게이트는 경유지 1,064건을 100% 제거하면서 정상 경로 손실은 0%였다.'
)

doc.add_heading('3.4.3 유사도 가중치 최적화', level=3)
doc.add_paragraph(
    '유사도 가중치는 2단계 격자탐색(grid search)으로 최적화하였다. '
    '1단계(coarse)에서는 route [0, 1] × sequence [0, 1] 범위를 0.05 간격으로 231개 시나리오를 탐색하고, '
    '2단계(fine)에서는 상위 영역(route [0.80, 1.00] × sequence [0.00, 0.20])을 0.01 간격으로 '
    '231개 시나리오를 추가 탐색하였다. mode 가중치는 1 − route − sequence로 결정된다.'
)
doc.add_paragraph(
    '각 가중치 조합에 대해 MNL 모형을 추정하고 test ρ²와 FPR을 평가하였다. '
    '최종적으로 mode = 0.83, sequence = 0.14, route = 0.03를 선택하였다. '
    '이는 수단구성 일치가 경로 구분의 가장 강력한 변별 요소임을 반영하며, '
    '정류장 순서와 노선 일치가 보조적으로 기여하는 구조이다.'
)

doc.add_heading('3.4.4 훈련 데이터 구성', level=2)
doc.add_paragraph(
    '매칭 결과를 OD 단위로 집계하여 선택확률(choice_prob = 해당 대안 매칭 통행수 / OD 전체 통행수)을 '
    '종속변수로 구성하였다. OD 기준 층화분할(8:2, seed=42)로 훈련·검증 데이터를 분리하였으며, '
    '최종 데이터 규모는 훈련 1,568,509건, 검증 392,501건(약 530,000 OD)이다.'
)

doc.add_heading('3.5 설명변수 정의', level=2)

table = doc.add_table(rows=10, cols=4, style='Table Grid')
headers = ['변수', '단위', '사양', '설명']
for i, h in enumerate(headers):
    table.rows[0].cells[i].text = h
    for paragraph in table.rows[0].cells[i].paragraphs:
        for run in paragraph.runs:
            run.bold = True

vars_data = [
    ['Total IVT', '분', '선형', '총 차내시간 (버스+철도+GTX 합산)'],
    ['Access walk', '분', 'ln(1+x)', '접근 도보시간 (첫 transit 전 도보)'],
    ['Egress walk', '분', 'ln(1+x)', '이탈 도보시간 (마지막 transit 후 도보)'],
    ['Transfer walk', '분', '선형', '환승 도보시간 (중간 도보 구간)'],
    ['Transfers', '회', '선형', '환승 횟수 (transit leg 수 − 1)'],
    ['Fare', '천원', '선형', '요금 (버스유형별 차등요금 반영)'],
    ['Has bus', '0/1', '더미', '버스 포함 여부 (ASC)'],
    ['Has train', '0/1', '더미', '도시철도 포함 여부 (ASC)'],
    ['Has GTX', '0/1', '더미', 'GTX 포함 여부 (ASC)'],
]
for r, row_data in enumerate(vars_data, 1):
    for c, val in enumerate(row_data):
        table.rows[r].cells[c].text = val

doc.add_paragraph()
doc.add_paragraph(
    '접근·이탈 도보시간은 중앙값이 0.12분(약 7초)으로 0 부근에 집중되어 있어 '
    '비선형 효과가 강하므로 로그 변환 ln(1+x)을 적용하였다. '
    '총 거리(total_distance)는 IVT와의 상관(r = 0.882, VIF = 5.47)으로 제거하였으며, '
    '대기시간(wait_time)은 OTP가 동일 출발시간대에 K-best 경로를 생성하여 '
    '대안 간 변이가 미미하고 환승횟수에 흡수되는 구조적 식별 불가 문제로 제거하였다.'
)

doc.add_heading('3.6 요금 산정', level=2)
doc.add_paragraph(
    '수도권 통합요금제 하에서는 동일 OD 내 대안경로 간 요금 차이가 0인 비율이 60.8%에 달하여, '
    '단순 거리비례 요금으로는 요금 파라미터를 식별할 수 없었다. '
    '이를 해결하기 위해 버스유형별 차등요금을 반영하였다: '
    '시내버스 1,200원, 광역버스 3,000원, 공항리무진 별도 요금 체계를 적용하여 '
    '동일 OD 내에서도 버스 유형에 따른 요금 차이를 생성하였다. '
    'GTX 요금은 기본 3,200원에 10km 초과 시 5km당 250원을 가산하였다.'
)

doc.add_heading('3.7 MNL 모형 추정', level=2)
doc.add_paragraph(
    '다항로짓(MNL) 모형은 효용 극대화 이론에 기반한 이산선택모형으로, '
    '대안 j의 효용함수는 다음과 같다:'
)
doc.add_paragraph('    V_j = β₁·IVT_j + β₂·ln(1+access_j) + β₃·ln(1+egress_j) + β₄·transfer_walk_j')
doc.add_paragraph('         + β₅·transfers_j + β₆·fare_j + β₇·has_bus_j + β₈·has_train_j + β₉·has_gtx_j')
doc.add_paragraph()
doc.add_paragraph(
    '선택확률은 P(j) = exp(V_j) / Σ_k exp(V_k)로 산출되며, '
    '통행수 가중 조건부 로짓으로 추정하였다. 학습 데이터의 로그우도 최대화를 통해 '
    '파라미터를 추정하고, 검증 데이터로 과적합 여부를 확인하였다.'
)

# ============================================================
# 4. 분석 결과
# ============================================================
doc.add_heading('4. 분석 결과', level=1)

doc.add_heading('4.1 유사도 가중치 민감도 분석', level=2)
doc.add_paragraph(
    '2단계 격자탐색 결과, coarse 탐색(231개 시나리오)에서 test ρ²의 범위는 0.441~0.497, '
    'FPR은 73.6~77.2%로 나타났다. 수단구성(mode) 가중치가 높은 영역에서 '
    '성능이 가장 높았으며, 수단 조합 일치가 경로 매칭의 지배적 변별 요소임이 확인되었다.'
)
doc.add_paragraph(
    'Fine 탐색(route 0.80~1.00, 231개 시나리오)에서는 ρ² 범위가 0.496~0.522로 수렴하였고, '
    '최적 영역 부근에서 ρ² spread 0.009, FPR spread 0.8%p로 높은 강건성을 확인하였다. '
    '베타 계수의 변동계수(CV)도 access, transfers, bus 등 주요 변수에서 3% 이내로 안정적이었다.'
)

doc.add_heading('4.2 MNL 모형 추정 결과', level=2)

# 결과 표
table = doc.add_table(rows=10, cols=4, style='Table Grid')
headers = ['변수', 'β', 't-stat', '유의수준']
for i, h in enumerate(headers):
    table.rows[0].cells[i].text = h
    for paragraph in table.rows[0].cells[i].paragraphs:
        for run in paragraph.runs:
            run.bold = True

results = [
    ['Total IVT (분)', '−0.0234', '−202.1', '***'],
    ['ln(1+Access walk 분)', '−3.190', '−1575.5', '***'],
    ['ln(1+Egress walk 분)', '−2.083', '−1556.3', '***'],
    ['Transfer walk (분)', '−0.067', '−117.3', '***'],
    ['Transfers (회)', '−3.398', '−1825.1', '***'],
    ['Fare (천원)', '−0.412', '−262.1', '***'],
    ['Has bus', '−3.456', '−1272.4', '***'],
    ['Has train', '+2.584', '+870.8', '***'],
    ['Has GTX', '−0.058', '−4.6', '***'],
]
for r, row_data in enumerate(results, 1):
    for c, val in enumerate(row_data):
        table.rows[r].cells[c].text = val

doc.add_paragraph()

doc.add_paragraph(
    '모든 변수가 1% 유의수준에서 통계적으로 유의하며, 부호가 이론적 기대와 일치한다. '
    '환승횟수(β = −3.398, t = −1825.1)가 가장 강한 억제 요인으로, '
    '환승 1회 추가 시 효용이 크게 감소함을 보여준다. '
    '이는 대중교통 이용자가 환승을 강하게 기피하는 행태를 반영한다.'
)
doc.add_paragraph(
    '철도 이용(has_train, β = +2.584)은 양의 ASC로, 도시철도에 대한 선호를 나타낸다. '
    '반면 버스(has_bus, β = −3.456)는 음의 ASC로, 버스 대안이 철도 대안 대비 기피됨을 시사한다. '
    'GTX(has_gtx, β = −0.058)는 매우 작은 음의 값으로, GTX가 일반 철도와 유사하게 평가됨을 보여준다.'
)
doc.add_paragraph(
    '접근 도보시간(β = −3.190)이 이탈 도보시간(β = −2.083)보다 절대값이 큰데, '
    '이는 출발지에서 정류장까지의 접근성이 경로선택에 더 큰 영향을 미침을 의미한다. '
    '환승 도보시간(β = −0.067)은 선형 사양으로 유의하였으나, 접근·이탈 도보에 비해 민감도가 낮았다.'
)
doc.add_paragraph(
    '요금(β = −0.412)은 버스유형별 차등요금 반영을 통해 성공적으로 식별되었다. '
    '요금 1,000원 증가 시 효용이 0.412 감소하며, 이를 IVT 가치로 환산하면 '
    '시간가치(VOT) = β_fare / β_IVT = 0.412 / 0.0234 ≈ 17.6분/천원, 즉 약 1,056원/분이다.'
)

doc.add_heading('4.3 모형 성능 평가', level=2)

table = doc.add_table(rows=6, cols=3, style='Table Grid')
headers = ['평가지표', '훈련', '검증']
for i, h in enumerate(headers):
    table.rows[0].cells[i].text = h
    for paragraph in table.rows[0].cells[i].paragraphs:
        for run in paragraph.runs:
            run.bold = True

perf = [
    ['McFadden ρ²', '0.5304', '0.5304'],
    ['Top-1 FPR', '72.50%', '72.50%'],
    ['Top-3 FPR', '96.1%', '96.1%'],
    ['RMSE', '0.2451', '0.2451'],
    ['파라미터 수', '9', '—'],
]
for r, row_data in enumerate(perf, 1):
    for c, val in enumerate(row_data):
        table.rows[r].cells[c].text = val

doc.add_paragraph()
doc.add_paragraph(
    'McFadden ρ² = 0.530으로 양호한 적합도를 보이며, 훈련·검증 간 ρ² 차이가 거의 없어 '
    '과적합이 발생하지 않았음을 확인하였다. '
    '이는 약 53만 OD에 대해 9개 파라미터만 추정하여 파라미터/OD 비율이 약 1:59,000으로 '
    '충분한 자유도가 확보되었기 때문이다.'
)
doc.add_paragraph(
    '제1순위 예측정확도(FPR Top-1) 72.5%는 최고 확률을 부여받은 대안이 실제 관측된 '
    '최다 선택 경로와 일치하는 비율이며, Top-3 96.1%는 상위 3개 대안 내에 '
    '실제 선택 경로가 포함되는 비율이다.'
)

doc.add_heading('4.4 수단분담률 재현', level=2)

table = doc.add_table(rows=4, cols=4, style='Table Grid')
headers = ['카테고리', '관측', '예측', '차이']
for i, h in enumerate(headers):
    table.rows[0].cells[i].text = h
    for paragraph in table.rows[0].cells[i].paragraphs:
        for run in paragraph.runs:
            run.bold = True

mode_share = [
    ['철도전용', '49.4%', '~49%', '<1%p'],
    ['버스전용', '42.5%', '~42%', '<1%p'],
    ['버스+철도', '8.0%', '~8%', '<1%p'],
]
for r, row_data in enumerate(mode_share, 1):
    for c, val in enumerate(row_data):
        table.rows[r].cells[c].text = val

doc.add_paragraph()
doc.add_paragraph(
    '수단분담률 재현에서도 주요 카테고리 모두 관측-예측 차이가 1%p 이내로 나타나, '
    '모형이 실제 수단선택 패턴을 정밀하게 재현함을 확인하였다.'
)

doc.add_heading('4.5 모형 사양 진화', level=2)

table = doc.add_table(rows=6, cols=4, style='Table Grid')
headers = ['버전', 'Test ρ²', 'Top-1 FPR', '주요 변경']
for i, h in enumerate(headers):
    table.rows[0].cells[i].text = h
    for paragraph in table.rows[0].cells[i].paragraphs:
        for run in paragraph.runs:
            run.bold = True

evolution = [
    ['v1 (초기)', '0.472', '70.3%', '초기 유사도 가중치'],
    ['v2 (가중치 최적화)', '0.487', '70.9%', '2단계 grid search'],
    ['v3 (차등요금)', '0.488', '71.8%', '버스유형별 요금 반영'],
    ['v4 (log walk)', '0.509', '72.2%', 'log(1+walk) + 모드별 IVT'],
    ['v5 (최종, K3)', '0.530', '72.5%', 'IVT 통합 + GTX 과추정 해소'],
]
for r, row_data in enumerate(evolution, 1):
    for c, val in enumerate(row_data):
        table.rows[r].cells[c].text = val

doc.add_paragraph()
doc.add_paragraph(
    '초기 모형(v1) 대비 최종 모형(v5)은 ρ²가 0.058 향상(+12.3%), '
    'Top-1 FPR이 2.2%p 개선되었다. 주요 개선 요인은 유사도 가중치 최적화, '
    '버스유형별 차등요금 반영, 도보시간 로그 변환, IVT 통합이다.'
)

# ============================================================
# 4.6 딥러닝 모형 비교
# ============================================================
doc.add_heading('4.6 딥러닝 모형 비교', level=2)

doc.add_paragraph(
    'MNL 모형의 선형 효용함수 한계를 보완하기 위해 5종의 딥러닝 경로선택 모형을 추정하고 '
    '성능을 비교하였다. 모든 모형은 MNL과 동일한 9개 설명변수, 동일한 OD 기준 학습/검증 분할(8:2), '
    '통행수 가중 교차엔트로피 손실함수를 사용하였다.'
)

doc.add_heading('4.6.1 딥러닝 모형 구조', level=3)

table = doc.add_table(rows=6, cols=4, style='Table Grid')
headers = ['모형', '구조', '파라미터 수', '특징']
for i, h in enumerate(headers):
    table.rows[0].cells[i].text = h
    for paragraph in table.rows[0].cells[i].paragraphs:
        for run in paragraph.runs:
            run.bold = True

dl_arch = [
    ['DNN', '11→64→32→1 (ReLU+Dropout)', '2,881', '순수 비선형 예측, 해석 불가'],
    ['TasteNet', 'Context→β(z), V=X·β(z)', '459', 'OD 거리에 따라 파라미터 가변 (해석 가능)'],
    ['ResLogit', 'V=X·β_MNL + DNN잔차(X)', '428', 'MNL 선형 효용 + 비선형 잔차 학습'],
    ['ASU-DNN', 'Alternative-Specific Utility DNN', '—', '대안별 독립 효용 네트워크'],
    ['L-MNL', 'Learning-MNL (DNN+MNL hybrid)', '—', 'DNN 표현학습 + MNL 선택확률'],
]
for r, row_data in enumerate(dl_arch, 1):
    for c, val in enumerate(row_data):
        table.rows[r].cells[c].text = val

doc.add_paragraph()
doc.add_paragraph(
    'TasteNet(Sifringer et al., 2020)은 컨텍스트 변수(OD 거리, 대안 수)로부터 '
    '개인별 파라미터 β(z)를 생성하여, 통행 거리에 따라 시간·비용 민감도가 달라지는 '
    '이질적 선호(taste heterogeneity)를 학습한다. '
    'ResLogit(Wong and Farooq, 2021)은 MNL의 선형 효용함수 위에 신경망 잔차를 학습하여, '
    '잔차의 크기로 MNL의 충분성을 평가할 수 있다. '
    'ASU-DNN은 각 대안에 독립적인 효용 네트워크를 부여하여 대안별 비선형 효과를 포착하고, '
    'L-MNL은 DNN의 표현학습 결과를 MNL의 효용함수에 추가 입력으로 활용하는 하이브리드 구조이다.'
)

doc.add_heading('4.6.2 성능 비교', level=3)

table = doc.add_table(rows=7, cols=5, style='Table Grid')
headers = ['모형', 'ρ²', 'Top-1 FPR', 'Top-3 FPR', 'RMSE']
for i, h in enumerate(headers):
    table.rows[0].cells[i].text = h
    for paragraph in table.rows[0].cells[i].paragraphs:
        for run in paragraph.runs:
            run.bold = True

dl_results = [
    ['MNL (기준)', '0.530', '72.5%', '96.5%', '0.245'],
    ['DNN', '0.558', '75.1%', '97.3%', '0.233'],
    ['TasteNet', '0.542', '73.9%', '96.9%', '0.242'],
    ['ResLogit', '0.554', '73.5%', '96.8%', '0.235'],
    ['ASU-DNN', '0.686', '76.0%', '97.5%', '0.224'],
    ['L-MNL', '0.555', '74.2%', '97.1%', '0.235'],
]
for r, row_data in enumerate(dl_results, 1):
    for c, val in enumerate(row_data):
        table.rows[r].cells[c].text = val

doc.add_paragraph()
doc.add_paragraph(
    '딥러닝 모형 중 ASU-DNN이 ρ² = 0.686, Top-1 FPR 76.0%로 가장 높은 성능을 보였다. '
    '이는 MNL 대비 ρ² +0.156(+29.4%), Top-1 FPR +3.5%p의 개선이다. '
    'ASU-DNN은 각 대안에 독립적인 효용 네트워크를 부여하여, '
    '대안별로 상이한 비선형 효과를 포착할 수 있는 유연한 구조가 성능 향상에 기여한 것으로 판단된다.'
)
doc.add_paragraph(
    'DNN(ρ² = 0.558), ResLogit(ρ² = 0.554), L-MNL(ρ² = 0.555)은 유사한 수준의 성능을 보였으며, '
    'MNL 대비 ρ² +0.024~0.028의 소폭 개선을 달성하였다. '
    'TasteNet(ρ² = 0.542)은 해석 가능한 구조임에도 MNL 대비 ρ² +0.012의 개선을 보여, '
    '파라미터의 컨텍스트 의존성이 효용 예측에 기여함을 확인하였다.'
)
doc.add_paragraph(
    'ResLogit의 경우, MNL β에 대한 잔차 네트워크의 기여가 ρ² +0.024에 그쳐, '
    'MNL의 선형 효용함수가 본 데이터에서 상당 부분 유효함을 시사한다. '
    '다만 모든 딥러닝 모형이 Top-1 FPR에서 MNL을 상회하여, '
    '비선형 효용함수가 경로선택 예측의 정확도를 일관되게 개선함을 확인하였다.'
)

doc.add_heading('4.6.3 해석 가능 모형의 파라미터 비교', level=3)

table = doc.add_table(rows=10, cols=4, style='Table Grid')
headers = ['변수', 'MNL β', 'TasteNet β', 'ResLogit β']
for i, h in enumerate(headers):
    table.rows[0].cells[i].text = h
    for paragraph in table.rows[0].cells[i].paragraphs:
        for run in paragraph.runs:
            run.bold = True

beta_comp = [
    ['Total IVT (분)', '−0.023', '−0.023', '−0.008'],
    ['ln(1+Access walk)', '−3.190', '−3.178', '−3.978'],
    ['ln(1+Egress walk)', '−2.083', '−1.570', '−1.964'],
    ['Transfer walk (분)', '−0.067', '−0.101', '+0.064'],
    ['Transfers', '−3.398', '−3.102', '−3.064'],
    ['Fare (천원)', '−0.412', '−0.351', '−0.980'],
    ['Has bus', '−3.456', '−4.049', '−3.616'],
    ['Has train', '+2.584', '+3.416', '+1.185'],
    ['Has GTX', '−0.058', '−3.147', '−0.614'],
]
for r, row_data in enumerate(beta_comp, 1):
    for c, val in enumerate(row_data):
        table.rows[r].cells[c].text = val

doc.add_paragraph()
doc.add_paragraph(
    'MNL, TasteNet, ResLogit 세 모형의 파라미터를 비교하면, '
    'IVT, 접근 도보, 환승횟수 등 주요 변수의 부호와 크기가 대체로 일관된다. '
    '다만 ResLogit의 IVT 파라미터(β = −0.008)가 MNL(−0.023)보다 작은데, '
    '이는 잔차 네트워크가 IVT의 비선형 효과 일부를 흡수한 결과로 해석된다. '
    'TasteNet의 GTX 파라미터(β = −3.147)가 MNL(−0.058)보다 크게 음수인 것은, '
    'OD 거리 컨텍스트에 따라 GTX 효용이 차별화되어 평균적으로 더 강한 억제 효과를 보이는 것이다.'
)

# ============================================================
# 4.7 SHAP 기반 변수 중요도 분석
# ============================================================
doc.add_heading('4.7 SHAP 기반 변수 중요도 분석', level=2)

doc.add_paragraph(
    '딥러닝 모형의 변수 중요도를 정량화하기 위해 SHAP(SHapley Additive exPlanations) 분석을 수행하였다. '
    'KernelExplainer를 사용하여 500개 배경 샘플과 1,000개 설명 샘플에 대해 '
    '각 변수의 SHAP value를 산출하였다. SHAP value는 게임이론의 Shapley value에 기반하여 '
    '각 변수가 예측에 기여하는 한계효과를 공정하게 배분한다.'
)

doc.add_heading('4.7.1 모형 간 변수 중요도 비교', level=3)

doc.add_paragraph(
    '5개 딥러닝 모형의 Mean |SHAP| 비교 결과, 모든 모형에서 공통적으로 '
    '다음의 변수 중요도 패턴이 관찰되었다:'
)
doc.add_paragraph(
    '(1) Has bus와 접근 도보시간(ln(1+access walk))이 가장 높은 중요도를 보였다. '
    '이는 버스 이용 여부와 정류장 접근성이 경로선택의 지배적 요인임을 의미한다.',
    style='List Number'
)
doc.add_paragraph(
    '(2) 환승횟수(transfers)와 이탈 도보시간(ln(1+egress walk))이 그 다음으로 중요하였다. '
    'MNL에서도 환승횟수가 가장 강한 억제 요인이었으므로, 딥러닝과 MNL의 해석이 일관된다.',
    style='List Number'
)
doc.add_paragraph(
    '(3) Has train과 has GTX는 중간 수준의 중요도를 보였으며, '
    '총 IVT와 요금(fare)은 상대적으로 낮은 중요도를 나타냈다. '
    '이는 수도권 대중교통에서 시간·비용보다 수단 유형과 접근성이 경로선택에 더 큰 영향을 미침을 시사한다.',
    style='List Number'
)
doc.add_paragraph(
    '(4) 환승 도보시간(transfer walk)은 모든 모형에서 가장 낮은 중요도를 보였다.',
    style='List Number'
)

doc.add_heading('4.7.2 SHAP Summary Plot 분석', level=3)

doc.add_paragraph(
    'DNN의 SHAP summary plot을 분석하면, '
    'Has bus는 높은 값(=버스 포함)일 때 강한 음의 SHAP value를, '
    '낮은 값(=버스 미포함)일 때 양의 SHAP value를 보여, '
    '버스 포함 경로의 선택확률이 감소하는 명확한 패턴을 확인하였다. '
    '접근 도보시간은 값이 클수록 음의 SHAP value가 증가하여, '
    '접근성이 나쁜 경로가 기피됨을 보여준다.'
)
doc.add_paragraph(
    'Has train은 높은 값(=철도 포함)일 때 양의 SHAP value를 보여 철도 선호를 확인하였으며, '
    '이는 MNL의 양의 ASC(β = +2.584)와 일관된 해석이다. '
    'Has GTX는 분포가 넓게 퍼져 있어, OD 특성에 따라 GTX의 효용이 양방향으로 작용함을 시사한다.'
)
doc.add_paragraph(
    'ASU-DNN의 경우 Has bus, 접근 도보, Has train 순으로 높은 중요도를 보였으며, '
    '특히 접근 도보시간의 SHAP value 분포가 다른 모형보다 넓어, '
    'ASU-DNN이 접근성의 비선형 효과를 더 적극적으로 학습하였음을 알 수 있다.'
)

doc.add_heading('4.7.3 MNL과 딥러닝의 해석 일관성', level=3)

doc.add_paragraph(
    'SHAP 분석 결과는 MNL 파라미터의 해석과 높은 일관성을 보였다. '
    'MNL에서 가장 큰 |β|를 가진 변수들(has_bus, transfers, access walk, has_train)이 '
    'SHAP 중요도에서도 상위권을 차지하였다. 이는 MNL의 선형 효용함수가 '
    '주요 변수의 영향 방향과 크기를 적절히 포착하고 있음을 보여준다. '
    '다만 딥러닝 모형은 변수 간 상호작용과 비선형 효과를 추가로 학습하여 '
    '예측 성능을 개선하는 것으로, SHAP value 분포의 비대칭성과 넓은 분산이 이를 반영한다.'
)

# ============================================================
# 4.8 최종 모형 선정
# ============================================================
doc.add_heading('4.8 최종 모형 선정', level=2)

doc.add_paragraph(
    '6개 모형(MNL + 딥러닝 5종)의 성능, 해석력, 실무 활용성을 종합적으로 평가하여 '
    '최종 모형을 선정하였다.'
)

table = doc.add_table(rows=7, cols=5, style='Table Grid')
headers = ['모형', 'ρ²', 'Top-1 FPR', '해석 가능성', '정책 활용성']
for i, h in enumerate(headers):
    table.rows[0].cells[i].text = h
    for paragraph in table.rows[0].cells[i].paragraphs:
        for run in paragraph.runs:
            run.bold = True

select_data = [
    ['MNL (K3)', '0.530', '72.5%', '◎', '◎'],
    ['DNN', '0.558', '75.1%', '×', '×'],
    ['TasteNet', '0.542', '73.9%', '○', '○'],
    ['ResLogit', '0.554', '73.5%', '○', '○'],
    ['ASU-DNN', '0.686', '76.0%', '×', '×'],
    ['L-MNL', '0.555', '74.2%', '△', '△'],
]
for r, row_data in enumerate(select_data, 1):
    for c, val in enumerate(row_data):
        table.rows[r].cells[c].text = val

doc.add_paragraph()
doc.add_paragraph(
    '본 연구의 최종 목적은 GTX-B·C 등 신규 노선 도입 시 수요 전환 시뮬레이션이며, '
    '이를 위해서는 요금·시간·환승 등 정책 변수의 한계효과를 해석할 수 있어야 한다. '
    'ASU-DNN이 ρ² = 0.686으로 가장 높은 예측 성능을 보였으나, '
    '블랙박스 구조로 인해 개별 변수의 정책적 함의를 도출할 수 없어 '
    '수요 시뮬레이션에 직접 활용하기 어렵다. DNN, L-MNL 역시 같은 한계를 갖는다.'
)
doc.add_paragraph(
    '이에 MNL(K3 사양)을 최종 모형으로 선정하였다. '
    'MNL은 ρ² = 0.530으로 딥러닝 대비 다소 낮지만, 9개 파라미터 모두 부호와 크기가 '
    '이론적 기대에 부합하고, 수단분담률을 1%p 이내로 재현하며, '
    '요금·시간 변화에 대한 탄력성을 직접 산출할 수 있다. '
    '무엇보다 SHAP 분석을 통해 딥러닝 모형들의 변수 중요도 순위가 '
    'MNL 파라미터의 해석과 일관됨을 확인하였으므로, '
    'MNL의 행태적 설명이 데이터의 실질적 패턴을 충실히 반영하고 있다고 판단하였다.'
)
doc.add_paragraph(
    '다만 TasteNet(ρ² = 0.542)은 해석 가능한 딥러닝 모형으로서 향후 확장 가능성을 갖는다. '
    'OD 거리에 따라 시간·비용 민감도가 변화하는 이질적 선호를 학습할 수 있어, '
    '단거리·장거리 통행의 차별화된 정책 효과 분석이 필요할 경우 활용할 수 있다.'
)

# ============================================================
# 5. 결론 및 시사점
# ============================================================
doc.add_heading('5. 결론 및 시사점', level=1)

doc.add_heading('5.1 연구 주요 결과 요약', level=2)

doc.add_paragraph(
    '본 연구는 수도권 스마트카드 약 3,700만 통행 기록과 OTP 대안경로를 유사도 매칭하여 '
    '경로선택 훈련 데이터를 자동 구축하고, MNL 및 5종의 딥러닝 모형을 추정하였다. '
    '주요 결과를 요약하면 다음과 같다.'
)
doc.add_paragraph(
    '첫째, 수단구성(0.83), 정류장 순서 LCS(0.14), 노선 Jaccard(0.03)의 3단계 복합유사도와 '
    '시퀀스 게이트(≥ 0.3)를 통해 약 53만 OD의 경로선택 관측치를 구축하였다. '
    '둘째, MNL(K3 사양)은 ρ² = 0.530, Top-1 FPR 72.5%를 달성하였으며, '
    '환승횟수(β = −3.40)가 가장 강한 억제 요인, 철도 이용(β = +2.58)이 양의 효용으로 나타났다. '
    '셋째, 딥러닝 모형 중 ASU-DNN이 ρ² = 0.686으로 최고 성능을 보였으나, '
    '해석 가능성과 정책 활용성을 종합 평가하여 MNL을 최종 모형으로 선정하였다. '
    'SHAP 분석으로 딥러닝과 MNL의 변수 중요도가 일관됨을 확인하여 MNL의 타당성을 교차 검증하였다.'
)

doc.add_heading('5.2 연구의 의의 및 기존 연구와의 차별점', level=2)

doc.add_paragraph(
    '본 연구는 기존 대중교통 경로선택 연구와 비교하여 다음의 차별점을 갖는다.'
)
doc.add_paragraph(
    '첫째, 대안경로 집합 생성과 매칭의 자동화이다. '
    '기존 연구는 대안경로 집합 생성에 GPS 추적(Marra and Corman, 2020)이나 '
    '설문 기반 RP 데이터(Tomhave and Khani, 2022)를 사용하여 표본 규모에 제약이 있었다. '
    '본 연구는 OTP(RAPTOR 알고리즘 기반)로 대안경로를 생성하고, '
    '3단계 복합유사도로 스마트카드 통행과 자동 매칭함으로써 '
    '설문 없이 약 53만 OD, 3,700만 통행 규모의 경로선택 데이터를 구축하였다. '
    '이는 기존 연구 대비 수십~수백 배 큰 규모이다.'
)
doc.add_paragraph(
    '둘째, 다수단(multimodal) 네트워크 전체를 포괄한다. '
    'Zhao et al.(2017)은 도시철도 단독 네트워크에서 확률적 배정을, '
    'Nassir et al.(2019)는 고빈도 서비스에 한정된 전략 기반 모형을 제안하였다. '
    '본 연구는 시내버스·도시철도·GTX가 혼재된 수도권 전체 네트워크를 대상으로 '
    '통합 경로선택 모형을 추정하여, 수단 간 환승을 포함한 복합 경로를 분석하였다.'
)
doc.add_paragraph(
    '셋째, MNL과 딥러닝의 체계적 비교 및 SHAP 기반 교차 검증이다. '
    '기존 딥러닝 경로선택 연구(Marra and Corman, 2025)는 단일 DL 모형과 PSL의 비교에 그쳤고, '
    'SHAP을 활용한 해석력 분석(Koushik et al., 2024; Tang et al., 2024)은 '
    '수단선택(mode choice)에 한정되었다. '
    '본 연구는 경로선택(route choice) 영역에서 5종의 DL 모형을 비교하고, '
    'SHAP으로 MNL 파라미터의 해석과 일관성을 검증한 최초의 사례이다.'
)
doc.add_paragraph(
    '넷째, 유사도 가중치의 체계적 최적화이다. '
    '기존 유사도 매칭 연구는 가중치를 연구자의 판단으로 설정하는 경우가 많았으나, '
    '본 연구는 2단계 격자탐색(coarse 231 + fine 231 시나리오)을 통해 '
    '가중치와 임계값을 MNL 성능 기준으로 체계적으로 최적화하였으며, '
    '가중치 변화에 대한 모형의 강건성(ρ² spread 0.009)을 정량적으로 검증하였다.'
)

doc.add_heading('5.3 학술적 시사점', level=2)

doc.add_paragraph(
    '본 연구의 학술적 시사점은 다음과 같다. '
    '첫째, 스마트카드 데이터와 경로탐색엔진의 결합이 SP 조사의 대안적 데이터 소스로서 '
    '유효함을 대규모 실증으로 검증하였다. 약 53만 OD에서 추정된 MNL 파라미터가 '
    '이론적 기대부호와 일치하고, 수단분담률을 1%p 이내로 재현함으로써 '
    '유사도 매칭 기반 관측치의 신뢰성을 확인하였다.'
)
doc.add_paragraph(
    '둘째, 대중교통 경로선택에서 Path Size Logit(PSL) 보정의 실효성이 제한적임을 실증하였다. '
    '이는 대중교통 경로가 도로 네트워크와 달리 정류장 중첩이 상대적으로 적어, '
    'PSL의 경로 중첩 보정 효과가 미미하기 때문으로 해석된다.'
)
doc.add_paragraph(
    '셋째, SHAP 분석을 통해 딥러닝 모형의 변수 중요도가 MNL 파라미터의 해석과 '
    '높은 일관성을 보임을 확인하였다. 이는 MNL의 선형 효용함수가 '
    '주요 변수의 영향 방향과 크기를 적절히 포착하고 있으며, '
    '딥러닝이 추가로 학습하는 것은 변수 간 상호작용과 비선형 효과임을 시사한다. '
    '이 결과는 Hillel et al.(2021)이 제기한 ML 모형의 해석력 부족 문제에 대해, '
    'SHAP을 통한 이산선택모형과의 교차 검증이 유효한 접근임을 보여준다.'
)

doc.add_heading('5.4 정책적 시사점', level=2)

doc.add_paragraph(
    '본 연구의 정책적 시사점은 다음과 같다. '
    '첫째, 본 연구의 파이프라인은 GTFS 데이터만 갱신하면 GTX-B·C 등 신규 노선 개통 시 '
    '수요 전환 시뮬레이션에 즉시 활용할 수 있다. '
    '스마트카드 데이터의 주기적 갱신을 통해 모형 파라미터를 지속적으로 업데이트할 수 있으며, '
    'SP 조사 대비 비용 효율적인 모형 유지·관리가 가능하다.'
)
doc.add_paragraph(
    '둘째, 환승횟수(β = −3.40)가 경로선택의 가장 강한 억제 요인으로 확인되어, '
    '환승 편의성 개선(환승 동선 단축, 환승 할인 확대 등)이 대중교통 이용 활성화에 '
    '가장 효과적인 정책 수단임을 시사한다. '
    '접근 도보시간의 비선형 효과(log 사양)는 정류장 접근성이 일정 수준을 넘으면 '
    '한계효용이 급감하므로, 정류장 신설보다 기존 정류장의 접근성 개선이 효율적임을 의미한다.'
)
doc.add_paragraph(
    '셋째, 수도권 통합요금제 하에서 버스유형별 차등요금이 경로선택에 유의한 영향을 미침을 '
    '확인하였다(β = −0.41). 이는 광역버스 요금 조정이나 GTX 요금 정책 수립 시 '
    '이용자의 경로 전환 효과를 정량적으로 예측할 수 있는 근거를 제공한다.'
)

doc.add_heading('5.5 연구 한계 및 향후 연구 방향', level=2)

doc.add_paragraph(
    '본 연구의 한계와 향후 연구 방향은 다음과 같다. '
    '첫째, 유사도 매칭 과정에서 선택확률과 복합유사도의 상관이 +0.76으로 높아 '
    '구조적 내생성이 존재한다. 도보시간이 짧은 경로일수록 높은 유사도를 부여받는 문제로, '
    '향후 매칭 단계의 독립적 검증이나 도구변수(IV) 접근이 필요하다.'
)
doc.add_paragraph(
    '둘째, 대기시간 파라미터가 구조적으로 식별되지 않았다. '
    'OTP가 동일 출발시간대에 K-best 경로를 생성하여 대안 간 대기시간 변이가 미미한 데 기인하며, '
    '시간대별 대안경로 생성이나 GTFS headway 기반 기대대기시간의 외생적 부여를 통해 '
    '개선할 수 있을 것이다.'
)
doc.add_paragraph(
    '셋째, GTX 포함 경로는 전체의 1.00%로 데이터가 적어 GTX 관련 파라미터의 신뢰성에 한계가 있다. '
    'Arriagada et al.(2025)이 제안한 경험학습(experiential learning) 모형과 같이, '
    '신규 노선 개통 전후의 통행 변화를 동태적으로 분석하는 접근이 보완적으로 필요하다.'
)
doc.add_paragraph(
    '넷째, TasteNet과 같은 해석 가능 딥러닝 모형의 심화 활용이 필요하다. '
    '통행 거리·시간대·이용자 특성에 따른 이질적 선호(taste heterogeneity) 분석을 통해 '
    'MNL의 동질적 선호 가정을 완화하고, 차별화된 정책 효과 분석이 가능할 것이다.'
)

# ============================================================
# 참고문헌
# ============================================================
doc.add_heading('참고문헌', level=1)

refs = [
    'Arriagada, J., Guevara, C.A., Munizaga, M. and Prato, C.G. (2025). "An experiential learning-based transit route choice model using large-scale smart-card data." Transportation, 52(4), pp. 1543-1568.',
    'Bast, H., Delling, D., Goldberg, A., Müller-Hannemann, M., Pajor, T., Sanders, P., Wagner, D. and Werneck, R. (2016). "Route planning in transportation networks." In Algorithm Engineering, Springer, pp. 19-80.',
    'Ben-Akiva, M. and Bierlaire, M. (1999). "Discrete choice methods and their applications to short term travel decisions." In Handbook of Transportation Science, Springer, pp. 5-33.',
    'Ben-Akiva, M. and Lerman, S.R. (1985). Discrete Choice Analysis: Theory and Application to Travel Demand. MIT Press.',
    'Cascetta, E., Nuzzolo, A., Russo, F. and Vitetta, A. (1996). "A modified logit route choice model overcoming path overlapping problems." In Proceedings of the 13th ISTTT, pp. 697-711.',
    'Delling, D., Pajor, T. and Werneck, R.F. (2015). "Round-based public transit routing." Transportation Science, 49(3), pp. 591-604.',
    'Dial, R.B. (1971). "A probabilistic multipath traffic assignment model which obviates path enumeration." Transportation Research, 5(2), pp. 83-111.',
    'Han, Y., Zegras, C., Pereira, F.C. and Ben-Akiva, M. (2022). "A neural-embedded discrete choice model: Learning taste representation with strengthened interpretability." Transportation Research Part B, 163, pp. 166-186.',
    'Hillel, T., Bierlaire, M., Elshafie, M.Z.E.B. and Jin, Y. (2021). "A systematic review of machine learning classification methodologies for modelling passenger mode choice." Journal of Choice Modelling, 38, 100221.',
    'Koushik, A., Manoj, M. and Nezamuddin, N. (2024). "SHapley Additive exPlanations for Explaining Artificial Neural Network Based Mode Choice Models." Transportation in Developing Economies, 10, Article 12.',
    'Lundberg, S.M. and Lee, S.I. (2017). "A unified approach to interpreting model predictions." In Advances in Neural Information Processing Systems 30, pp. 4765-4774.',
    'Marra, A.D. and Corman, F. (2020). "Determining an efficient and precise choice set for public transport based on tracking data." Transportation Research Part A, 142, pp. 168-186.',
    'Marra, A.D. and Corman, F. (2025). "Modelling route choice in public transport with deep learning." Transportation, online first.',
    'McFadden, D. and Train, K. (2000). "Mixed MNL models for discrete response." Journal of Applied Econometrics, 15(5), pp. 447-470.',
    'Nassir, N., Hickman, M. and Ma, Z.L. (2019). "A strategy-based recursive path choice model for public transit smart card data." Transportation Research Part B, 126, pp. 528-548.',
    'Pelletier, M.P., Trépanier, M. and Morency, C. (2011). "Smart card data use in public transit: A literature review." Transportation Research Part C, 19(4), pp. 557-568.',
    'Sifringer, B., Lurkin, V. and Alahi, A. (2020). "Enhancing discrete choice models with representation learning." Transportation Research Part B, 140, pp. 236-261.',
    'Tan, R., Adnan, M., Lee, D.H. and Ben-Akiva, M.E. (2015). "New Path Size Formulation in Path Size Logit for Route Choice Modeling in Public Transport Networks." Transportation Research Record, 2538(1), pp. 11-16.',
    'Tang, C., Fu, Q. and Ma, C. (2024). "Predicting travel mode choice with a robust neural network and Shapley additive explanations analysis." IET Intelligent Transport Systems, 18(7), pp. 1339-1354.',
    'Tomhave, B.J. and Khani, A. (2022). "Refined choice set generation and the investigation of multi-criteria transit route choice behavior." Transportation Research Part A, 155, pp. 484-500.',
    'Wong, M. and Farooq, B. (2021). "ResLogit: A residual neural network logit model for data-driven choice modelling." Journal of Choice Modelling, 38, 100262.',
    'Zhao, J., Zhang, F., Tu, L., Xu, C., Shen, D., Tian, C., Li, X.Y. and Li, Z. (2017). "Estimation of Passenger Route Choice Pattern Using Smart Card Data for Complex Metro Systems." IEEE Transactions on Intelligent Transportation Systems, 18(4), pp. 790-801.',
]

for i, ref in enumerate(refs, 1):
    doc.add_paragraph(f'[{i}] {ref}')

# ── 저장 ──
output_path = r'C:\Research\6.route_choice_simulation\paper\paper_draft.docx'
doc.save(output_path)
print(f'저장 완료: {output_path}')
